[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install python-telegram-bot==20.7 qrcode==7.4.2 Pillow==10.4.0 requests==2.32.3 psutil==5.9.8"]

[start]
cmd = "python -u MENTALCHEATLOBBY.PY"
